In [23]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [24]:
#load ann trained model,scaler pickle,one hot encoder
model=load_model('model.h5')
#load encoders and scaler
with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [35]:
#example input data
input_data={
    'CreditScore':600,
    'Geography':'Germany',
    'Gender':'Male',
    'Age':60,
    'Tenure':3,
    'Balance':120000,
    'NumOfProducts':1,
    'HasCrCard':1,
    'IsActiveMember':0,
    'EstimatedSalary':50000
}

In [36]:
geo_encoded=onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

d:\GEN AI\room\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               0.0                1.0              0.0

In [37]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,Germany,Male,60,3,120000,1,1,0,50000

In [38]:
#encode categorical variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,Germany,1,60,3,120000,1,1,0,50000

In [39]:
#concat of categorical vacriable geography
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,60,3,120000,1,1,0,50000,0.0,1.0,0.0

In [40]:
##Scaling the input data
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.52129985,  0.92664469,  2.00495283, -0.69732363,  0.69025669,
        -0.90664753,  0.6426278 , -1.03695035, -0.87079315, -1.0035079 ,
         1.72916742, -0.57369185]])

In [41]:
#prediction
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 52ms/step

array([[0.9464869]], dtype=float32)

In [42]:
prediction_proba=prediction[0][0]

In [43]:
prediction_proba

0.9464869

In [44]:
if prediction_proba>0.5:
    print("the customer likely to churn")
else:
    print("the customer not likely to churn")

the customer likely to churn